sudo pacman -Syu --needed \
  bluedevil \
  breeze \
  breeze-gtk \
  discover \
  drkonqi \
  kactivitymanagerd \
  kde-cli-tools \
  kdecoration \
  kde-gtk-config \
  kdeplasma-addons \
  kgamma5 \
  khotkeys \
  kinfocenter \
  kmenuedit \
  kscreen \
  kscreenlocker
  ksystemstats \
  kwin \
  kwrited \
  libkscreen \
  libksysguard \
  plasma-browser-integeration \
  plasma-desktop \
  plasma-disks \
  plasma-firewall \
  plasma-integeration \
  plasma-nm \
  plasma-pa \
  plasma-sdk \
  plasma-systemmonitor \
  plasma-workspace \
  plasma-workspace-wallpapers \
  polkit-kde-agent \
  powerdevil \
  sddm-kcm \
  systemsettings \
  xdg-desktop-portal-kde \
  ark \
  cantor \
  dolphin \
  dolphin-plugins \
  elisa \
  vlc \
  ffmpeg \
  ffmpegthumbs \
  filelight \
  gwenview \
  kalarm \
  kalgebra \
  kalzium \
  kamera \
  kamoso \
  kate \
  kcalc \
  kcolorchooser \
  kcron \
  kdeconnect \
  kdegraphics-mobipocket \
  kdegraphics-thumbnailers \
  kdenetwork-filesharing \
  kdf \
  kdialog \
  keditbookmarks \
  kfind \
  kget \
  kgpg \
  kdesdk-kioslaves \
  kdesdk-thumbnailers \
  kio-extras \
  kio-gdrive \
  knotes \
  gimp \
  kcompare \
  konsole \
  ktimer \
  okular \
  partitionmanager \
  print-manager \
  spectacle \
  svgpart \
  zeroconf-ioslave \
  dnsmasq \
  packagekit-qt5 \
  bluez \
  bluez-utils \
  pulseaudio \
  pulseaudio-bluetooth \
  pulseaudio-zeroconf \
  pavucontrol
